### ISSUE TITLE
Can't load any notebook

### ISSUE THREAD

**Issue by EtienneT** [marimo-team/vscode-marimo#61]
I created a new notebook using `marimo edit test.py`, then close marimo and I try to load it in vscode, both with `Open as vscode notebook` and `Start in marimo editor`, but both don't work.  Marimo is installed in the virtual environment using uv in the pyproject.toml.  But when I try to load the notebook 

When I open it as a vscode notebook, it is stuck at loading:

![Image](https://github.com/user-attachments/assets/2ed3efd6-7b7c-491c-8b86-cf91757d8cca)

Then here is the log in Output for marimo

```
2024-12-13 13:19:44.043 [info] marimo extension is now active!
2024-12-13 13:19:44.043 [info] [server-manager]: Could not recover any state
2024-12-13 13:19:44.043 [info] Opened notebook document marimo-notebook
2024-12-13 13:19:44.043 [info] Showing a new marimo notebook
2024-12-13 13:19:44.043 [info] Checking server...
2024-12-13 13:19:44.043 [info] [server-manager]: Starting server...
2024-12-13 13:19:44.043 [info] Using interpreter: c:\work\ML\notebooks\.venv\Scripts\python.exe
2024-12-13 13:19:44.043 [info] Using interpreter: c:\work\ML\notebooks\.venv\Scripts\python.exe
2024-12-13 13:19:47.923 [info] [server-manager]: Server started at port 2818
```

I tested in vscode normal and vscode insider.  Both have the same problem.

**Comment by davidgasquez** [comment]
Hitting this error now... I've been working for a couple of hours without issues, but something made it "break".

**Comment by gabrielgrant** [comment]
This looks to be a duplicate of #35 right?

**Comment by EtienneT** [comment]
Hum it seems similar yeah.

**Comment by mscolnick** [comment]
Does stopping and restarting the server fix this?

Can you verify the server is healthy through the Command Palette `marimo: Show marimo status`

**Comment by kimmolinna** [comment]
For me It looks like a uvicorn-problem. I can start a notebook in run mode but not in edit mode.

**Comment by mscolnick** [comment]
I just released version 0.5.0 with an updated guide on particular vscode settings: https://github.com/marimo-team/vscode-marimo#python-configuration

If anyone is still experiencing issues, it might be worth trying a different combination of settings.

**Comment by EtienneT** [comment]
I installed version 0.5.0.

I tried multiple things to try to make it work, setting "python.defaultInterpreterPath" in my workspace, also "marimo.pythonPath".  I tried changing the default port, I have set those properties to all the possible values from the configuration page you suggested:

```
{
  "marimo.marimoPath": "uvx marimo",
  "marimo.sandbox": true
}
```

But nothing works.  I always get the following log:

![Image](https://github.com/user-attachments/assets/675d5a43-4055-41ab-988c-a9c13fae5335)

But when I open the url from the log in my browser, it loads correctly.  So maybe we are not waiting long enough for the heatlh check?

I even tried in a completely blank workspace where those are the only settings I set and still the same problem:

```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"marimo.marimoPath": "uvx marimo",
		"marimo.sandbox": true,
		"marimo.pythonPath": "${workspaceFolder}/.venv/bin/python"
	}
}
```

I did all my tests in vscode insiders.  But last time I tried in normal vscode and it did the same thing, so I am not sure it is relevant to test it there again.

**Comment by dltmtt** [comment]
I think you might be right in assuming we are not waiting enough before fetching, I got the same intuition and changed the code to retry a few times before throwing an error and got it working on a simple notebook.

Here's the modification I made:
```ts
async function fetchMarimoStartupValues(port) {
  const url = asURL(await composeUrl(port));
  let response;
  const maxRetries = 5;
  const delay = 1000;

  for (let i = 0; i < maxRetries; i++) {
    try {
      response = await fetch(url.toString());
      if (response.ok) break;
    } catch (e) {
      logger.error(`Attempt ${i + 1}: Could not fetch ${url}. Is the server running?`);
      if (i === maxRetries - 1) {
        throw new Error(`Could not fetch ${url}. Is the server running?`);
      }
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }

  // ...rest of the function (unchanged)
}
```
For reference, it took 3 retries on the simple notebook, but 5 were not enough for a slightly longer file in a larger project, so `maxRetries` and `delay` should be adjusted.

@mscolnick – you know the codebase better, do you think `fetchMarimoStartupValues` could be called later without needing to resort to timeouts? I don't really like this approach, it was just a quick test to get it to work.

**Comment by wgpsutherland** [comment]
> So maybe we are not waiting long enough for the heatlh check?

I think this intuition is correct. When trying to start the server in the vscode extension I get the following error A, but this is then immediately followed by B. When I then visit http://localhost:2818/ the server is running correctly

![Image](https://github.com/user-attachments/assets/745f26df-edf7-4bb5-a874-fb5a875c6cad)

**Comment by atlaslabsworld** [comment]
Bump this thread because this is the only ```Marimo``` extension in ```VSCode```

**Comment by EtienneT** [comment]
> Bump this thread because this is the only `Marimo` extension in `VSCode`

This is the official extension.  Not too sure why this extension is not more of a priority.

**Comment by mscolnick** [comment]
@EtienneT what version of marimo are you using?

**Comment by EtienneT** [comment]
> [@EtienneT](https://github.com/EtienneT) what version of marimo are you using?
> 
> I use this every day and it works fine for me. (I don't use the native vscode notebook, but rather --watch)

Even creating a new marimo notebook using the extension doesn't work and it gets stuck at loading.

How do you setup to use --watch with the extension?

**Comment by mscolnick** [comment]
@EtienneT on the latest version of marimo, I start the editor inside VSCode side-by-side with the read-only panel. And I edit the marimo file directly

**Comment by mscolnick** [comment]
I just released `v0.5.1` with hopefully some better resiliency to startup

**Comment by EtienneT** [comment]
Thank you for the fix!

I tested both vscode and vscode insiders.  Normal vscode works now!  But in vscode insiders, I am still having problems with the "Open as VScode notebook" button.

Related problems inside vscode insiders:

Now starting a notebook with this button works: 

![Image](https://github.com/user-attachments/assets/1b06cf89-c3dc-4110-b1dc-2e1c2e649bbd)

But, creating a new notebook using this button does not:

![Image](https://github.com/user-attachments/assets/1755ecd5-1e86-4e46-911a-045264cfbe79)

It creates the file, it is not listed in the list of notebooks in the marimo extension (if I restart vscode insider, then it will get listed).  It stays at Loading... in the editor pane:

![Image](https://github.com/user-attachments/assets/066822ed-84d2-45e4-87c6-d730e1c40238)

I can open the server url in my browser and use the notebook though, but in vscode, it doesn't work.

Trying to open any notebook with this button will stay at Loading in the vscode notebook:

![Image](https://github.com/user-attachments/assets/2580a7bf-dec9-4d0b-93c3-6c01a2c9bb26)

**Comment by Semphora** [comment]
I can not confirm, that this works on normal vscode. I'm experiencing the same stuck on load issue today with marimo 0.5.1 on windows 10, with vscode 1.98.2.

**Comment by fuchse-ego** [comment]
Hey, I'm also affected. There's a "strange" message in the marimo output panel:
```
2025-04-03 15:17:57.173 [info] [server-manager]: Server started at port 2819
2025-04-03 15:17:58.066 [info] Using interpreter: c:\development\projects\coil-analysis\venv\Scripts\python.exe
2025-04-03 15:18:04.264 [error] [server-manager] Unexpected error starting server {"error":{}}
2025-04-03 15:18:04.264 [error] [server-manager] Unexpected error starting server {"error":{},"state":"started"}
```

I'm on Win11 and VSCode 1.98.2 and plugin version 0.5.1.

**Comment by mscolnick** [comment]
Closing as duplicate of #35
